### PR TITLE
Fix timestamp precision for select

### PR DESCRIPTION
**Pull request by cccross**

### CODE REVIEW

**Comment by markusahlstrand** [comment]
Thanks for the PR @cccross ! 

I'll add some tests for this to make sure that it's consistent between PG and mysql.

**Comment by christian-castillo-baires-dev** [comment]
> Thanks for the PR @cccross !
> 
> I'll add some tests for this to make sure that it's consistent between PG and mysql.

Nice! thanks.

**Comment by cccross** [comment]
> Thanks for the PR @cccross !
> 
> I'll add some tests for this to make sure that it's consistent between PG and mysql.

Nice! Thanks.

**Comment by markusahlstrand** [comment]
Turns out that we need truncate the date on the writes as well, so there's another fix that is needed as well. I'll merge this PR first and then add the other fix before releasing a new version

**Pull request merged**
