### PR TITLE
fix: use rds data api to commit and rollback transactions

### LINKED ISSUE #109: The library does not close database transactions correctly
When using transactions, the library sends `COMMIT` sql, instead of using commit transaction [method of RDS](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_CommitTransaction.html).

Since the transaction is not committed via RDS method, the transaction will be kept open in AWS RDS for 5mins, which means that the number of connections will keep increasing. Eventually, connections will start to drop.

This issue was well described in https://github.com/jeremydaly/data-api-client/issues/37#issuecomment-1169229906.

> Our solution was to properly close transactions with function as we were using a lot of transactions but implementation of knex-aurora-data-api-client for "starting transaction" was properly calling DataAPI function, but one for "commiting transaction" was only sending COMMIT command and not using commitTransaction function of data-api-client. And Data API is waiting 5 minutes for not committed transactions to end. Data in database was already committed (thanks to COMMIT command), but connection to Data API was not considered as committed transactions as Data API requires to call explicit commit of rollback (and you don't need to call SQL COMMIT). After changing implementation our problem of hitting 500 connections was solved immediately and now we are at maximum 20 connections. Hopefully it would help somebody. Don't know what is AppSync using.

This can be reproduced by sending sequential transactions - the number of connections keeps increasing, until they start to be dropped (timeout).

### PR DESCRIPTION
**Pull request by CoDanny**
fixes #109

### CODE REVIEW

**Comment by markusahlstrand** [comment]
Hi @CoDanny !

Thanks for the PR! It looks like there's just two small linting errors. Could you fix those and I can merge it?

**Comment by CoDanny** [comment]
> Thanks for the update. Still a few lint errors in there. Let me know if you want me to patch them :)

Sorry about that. Fixed now and this time I didn't forget to run linter locally :)

**Review by markusahlstrand — APPROVED** [review]
Looks good!

**Comment by markusahlstrand** [comment]
I noticed that a integration test was failing and just patched it.. Seem like npm is having a bad day, but I'll give another try to publish it later today.

**Comment by markusahlstrand** [comment]
Published now :)

**Pull request merged**
