### PR TITLE
Implements and tests the knex.first(...) command

### PR DESCRIPTION
**Pull request by chasent**
First of all, thank you for making this library!
While using it, I found that the .first(...) command returned incorrect data.
I have implemented the minimum amount of code in the processResponse function to make the .first(...) command work, as well as the relevant tests.

### CODE REVIEW

**Comment by markusahlstrand** [comment]
Hi, thanks for the contribution! I somehow missed that the PR, will have a look at it straight away :)

**Comment by markusahlstrand** [comment]
It looks like the linter would like to use array destructuring. You think you can update that and maybe merge the updates from the master branch and it should be good to go :)

**Comment by chasent** [comment]
Whoops, sorry, I forgot to run the linter before committing. I have fixed the linter error and rebased the branch onto master.
Thank you 😃

**Comment by russell-avowow** [comment]
Hey guys, and update on this one?

**Comment by russellr922** [comment]
Hey guys, any update on this one?

**Comment by markusahlstrand** [comment]
Sorry for the delay! I'll have a look again :)

**Pull request merged**
