### PR TITLE
Decrease npm package size

### PR DESCRIPTION
**Pull request by husa**
include only source files in npm package(index.js will be included as it's "main")

relates to #6 

using this command to test
```sh
mkdir test-size && cd test-size && 
npm init -y && 
npm i knex-aurora-data-api-client && 
du -hs node_modules/knex-aurora-data-api-client && 
cd .. && rm -rf test-size
```

### CODE REVIEW

**Comment by markusahlstrand** [comment]
It seems that I missed to remove node_modules from the integration folder so it's pulling all the AWS Cdk stuff. I'll fix that

**Comment by markusahlstrand** [comment]
Added a npm-ignore file which seemed like the best option. Hope that works out.

**Comment by markusahlstrand** [comment]
Ahh, now I saw the commit you did with files :) Too much going on today. That should work just fine. I'll go ahead and merge it.

**Comment by husa** [comment]
@markusahlstrand 👍

**Pull request merged**
