### PR TITLE
format custom `output` parameters as native MySQL client

### PR DESCRIPTION
**Pull request by husa**
fix `hasTable` always returning `false`

### CODE REVIEW

**Comment by husa** [comment]
Looks like regression after #27 
Migrations for MySQL now don't work.

**Comment by markusahlstrand** [comment]
Thanks for the PR :) I'll have a look at it at the latest tomorrow.

**Comment by husa** [comment]
Thanks, in the meantime switched to v1.2.2

**Comment by markusahlstrand** [comment]
It would be great if we could write an integration test around this to make sure we don't break it again in future releases. Do you know what the root cause of the issue is? Which queries would this change affect?

**Comment by markusahlstrand** [comment]
Will be fixed by #32 . If it's ok with you I'll go ahead and close this PR?

**Comment by husa** [comment]
@markusahlstrand absolutely, as long as it's fixed

**Comment by markusahlstrand** [comment]
Pushed 1.2.5 to npm now, so I can wait until you verified that the new version works.

**Comment by husa** [comment]
yep, everything's fine. Safe to close.

**Pull request closed without merging**
